### ISSUE TITLE
go get issue 

### ISSUE THREAD

**Issue by gengmao** [alde/eremetic#34]
Hi, 

I found this project looks perfect for our usage and tried to build on my Mac. But I hit a `go get` error like below. 
```
mao-mac:eremetic mao (master) $ export GOPATH=$(pwd)
mao-mac:eremetic mao (master) $ export PATH=$GOPATH/bin:$PATH
mao-mac:eremetic mao (master) $ make
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go generate
Cannot read bindata.go open bindata.go: no such file or directory
go get -t ./...
src/github.com/alde/eremetic/routes/routes.go:9:2: no buildable Go source files in /Users/mao/Development/eremetic/src/github.com/alde/eremetic/assets
src/github.com/kr/text/mc/mc.go:13:2: cannot find package "github.com/kr/pty" in any of:
	/usr/local/go/src/github.com/kr/pty (from $GOROOT)
	/Users/mao/Development/eremetic/src/github.com/kr/pty (from $GOPATH)
src/github.com/spf13/viper/remote/remote.go:12:2: cannot find package "github.com/xordataexchange/crypt/config" in any of:
	/usr/local/go/src/github.com/xordataexchange/crypt/config (from $GOROOT)
	/Users/mao/Development/eremetic/src/github.com/xordataexchange/crypt/config (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
	/usr/local/go/src/golang.org/x/text/encoding (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/charmap (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:8:2: cannot find package "golang.org/x/text/encoding/japanese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/japanese (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/japanese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:9:2: cannot find package "golang.org/x/text/encoding/korean" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/korean (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/korean (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:10:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/simplifiedchinese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:11:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/traditionalchinese (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/traditionalchinese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:12:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/unicode (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/encoding/unicode (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:22:2: cannot find package "golang.org/x/text/transform" in any of:
	/usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/text/transform (from $GOPATH)
src/golang.org/x/net/http2/h2i/h2i.go:36:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/Users/mao/Development/eremetic/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
make: *** [deps] Error 1
```

I couldn't figure out (sorry I am new to golang), can you please help? 

Thanks,
Mao

**Comment by alde** [comment]
You need to run go generate first (only the first time)

Easiest way is to use the make file. Will update the readme when I have time :)

Thanks for bringing it to my attention, easy to get blind to documentation when developing.

**Comment by alde** [comment]
I have now updated the readme, hopefully that makes the process clearer.

**Comment by gengmao** [comment]
Thanks @alde. However I still have issue following the build steps in README. 
```
mao-mac:eremetic mao (master) $ go get github.com/jteeuwen/go-bindata/...
mao-mac:eremetic mao (master) $ go get github.com/elazarl/go-bindata-assetfs/...
mao-mac:eremetic mao (master) $ go generate
assets/assets.go
Cannot read bindata.go open bindata.go: no such file or directory
mao-mac:eremetic mao (master) $ go get -t ./...
package camlistore.org/pkg/throttle: cannot find package "camlistore.org/pkg/throttle" in any of:
	/usr/local/go/src/camlistore.org/pkg/throttle (from $GOROOT)
	/Users/mao/Development/eremetic/src/camlistore.org/pkg/throttle (from $GOPATH)
```
Actually I found the build steps are same as `make`... Also I found `go get -t ./...` waited for a while then output error.

**Comment by alde** [comment]
does it work to manually run `go get camlistore.org/pkg/throttle`?

**Comment by gengmao** [comment]
No. 
```
mao-mac:eremetic mao (master) $ go get camlistore.org/pkg/throttle
package camlistore.org/pkg/throttle: cannot find package "camlistore.org/pkg/throttle" in any of:
	/usr/local/go/src/camlistore.org/pkg/throttle (from $GOROOT)
	/Users/mao/Development/eremetic/src/camlistore.org/pkg/throttle (from $GOPATH)
```

**Comment by alde** [comment]
Ok, weird.

I'll have to check at the office tomorrow if I can find someone with a mac (although that should not matter). And also to find what dependency is depending on throttle.

**Comment by gengmao** [comment]
Thank you for quick response!

**Comment by gengmao** [comment]
FYI. I reproduced the issue on Ubuntu too. Will adjust the subject. 
```
ubuntu@ec2:~$ go version
go version go1.5.2 linux/amd64
ubuntu@ec2:~$ git clone https://github.com/alde/eremetic.git
Cloning into 'eremetic'...
remote: Counting objects: 504, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 504 (delta 1), reused 0 (delta 0), pack-reused 500
Receiving objects: 100% (504/504), 731.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (249/249), done.
Checking connectivity... done.
ubuntu@ec2:~$ cd eremetic/
ubuntu@ec2:~/eremetic$ ls
assets    db      eremetic.go       eremetic.yml.example  generate.go  Makefile  README.md  scheduler  templates  version.go
database  docker  eremetic_test.go  formatter             handler      misc      routes     static     types
ubuntu@ec2:~/eremetic$ export GOPATH=$(pwd)
ubuntu@ec2:~/eremetic$ export PATH=$GOPATH/bin:$PATH
ubuntu@ec2:~/eremetic$ go get github.com/jteeuwen/go-bindata/...
ubuntu@ec2:~/eremetic$ go get github.com/elazarl/go-bindata-assetfs/...
ubuntu@ec2:~/eremetic$ go generate
Cannot read bindata.go open bindata.go: no such file or directory
ubuntu@ec2:~/eremetic$ go get -t ./...
src/github.com/alde/eremetic/routes/routes.go:9:2: no buildable Go source files in /home/ubuntu/eremetic/src/github.com/alde/eremetic/assets
src/github.com/kr/text/mc/mc.go:13:2: cannot find package "github.com/kr/pty" in any of:
	/usr/local/go/src/github.com/kr/pty (from $GOROOT)
	/home/ubuntu/eremetic/src/github.com/kr/pty (from $GOPATH)
src/github.com/spf13/viper/remote/remote.go:12:2: cannot find package "github.com/xordataexchange/crypt/config" in any of:
	/usr/local/go/src/github.com/xordataexchange/crypt/config (from $GOROOT)
	/home/ubuntu/eremetic/src/github.com/xordataexchange/crypt/config (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
	/usr/local/go/src/golang.org/x/text/encoding (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/charmap (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:8:2: cannot find package "golang.org/x/text/encoding/japanese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/japanese (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/japanese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:9:2: cannot find package "golang.org/x/text/encoding/korean" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/korean (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/korean (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:10:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/simplifiedchinese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:11:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/traditionalchinese (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/traditionalchinese (from $GOPATH)
src/golang.org/x/net/html/charset/table.go:12:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
	/usr/local/go/src/golang.org/x/text/encoding/unicode (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/encoding/unicode (from $GOPATH)
src/golang.org/x/net/html/charset/charset.go:22:2: cannot find package "golang.org/x/text/transform" in any of:
	/usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/text/transform (from $GOPATH)
src/golang.org/x/net/http2/h2i/h2i.go:36:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/home/ubuntu/eremetic/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
```

**Comment by keis** [comment]
I think this could be a GOPATH issue because we see these weird paths `/home/ubuntu/eremetic/src/github.com/alde/eremetic/assets` (eremetic twice)

Could you try setting it to `$HOME/gocode` and then clone into `$HOME/gocode/src/github.com/alde/eremetic` and build from there?

**Comment by alde** [comment]
Ah yes, the projects assume that you have the project checked out in
`$GOPATH/src/github.com/alde/eremetic`

I don't know any way to get around that.

**Comment by gengmao** [comment]
Thank you! Checking the project into `$GOPATH/src/github.com/alde/eremetic` resolved my issue. 
```
ubuntu@ec2:~/gocode/src/github.com/alde/eremetic$ make docker
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go generate
removed ‘assets/assets.go’
Cannot read bindata.go open bindata.go: no such file or directory
go get -t ./...
CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.Version '0.8.0-10-g206253b' -X main.BuildDate '2015-12-08_17:46:28'" -a -installsuffix cgo -o docker/eremetic
# github.com/alde/eremetic
link: warning: option -X main.Version 0.8.0-10-g206253b may not work in future releases; use -X main.Version=0.8.0-10-g206253b
link: warning: option -X main.BuildDate 2015-12-08_17:46:28 may not work in future releases; use -X main.BuildDate=2015-12-08_17:46:28
docker build -t alde/eremetic:0.8.0-10-g206253b docker
Sending build context to Docker daemon 17.78 MB
Step 1 : FROM alpine:3.2
3.2: Pulling from library/alpine
8a648f689ddb: Pull complete
Digest: sha256:35263e39831e23388d2a617fc485ca8503215924f7e6373e4f5abd377d6fa551
Status: Downloaded newer image for alpine:3.2
 ---> 8a648f689ddb
Step 2 : RUN mkdir -p /opt/eremetic
 ---> Running in 276b3ecb93c3
 ---> f3ce7c8af67b
Removing intermediate container 276b3ecb93c3
Step 3 : COPY eremetic /opt/eremetic/eremetic
 ---> 6f2e497ec1f7
Removing intermediate container 97825e45d548
Step 4 : COPY marathon.sh /marathon.sh
 ---> 6f07900dcfea
Removing intermediate container ca9b3f35a1cc
Step 5 : WORKDIR /opt/eremetic
 ---> Running in fc92e31f38df
 ---> e207f6eac365
Removing intermediate container fc92e31f38df
Step 6 : CMD /marathon.sh
 ---> Running in fa2d79e22f13
 ---> b6754ea9f043
Removing intermediate container fa2d79e22f13
Successfully built b6754ea9f043
```
